# Generated by Django 2.2.7 on 2020-10-25 04:05

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0024_alter_jsonfield_to_jsonbfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_accessed',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
